data:
  lookback_days: 1825  # 5 years of data
  save_path: data_output/fetched_data_for_training
  processed_path: data_output/processed_data
  train_path: data_output/processed_data/train
  validation_path: data_output/processed_data/validation
  test_path: data_output/processed_data/test
  results_path: data_output/trained_models
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  symbol: XAUUSD
  timeframes:
    - H1
features:
  technical_indicators:
  - indicators:
    - name: ema
      params:
      - 9
      - 21
      - 55
      - 200
    - name: macd
      params:
        fast: 12
        signal: 9
        slow: 26
    type: trend
  - indicators:
    - name: rsi
      params:
      - 14
    type: momentum
  - indicators:
    - name: bbands
      params:
        length: 20
        std: 2
    - name: atr
      params:
      - 14
    type: volatility
logging:
  level: INFO
  log_folder: data_output/logs
  log_to_file: true
model:
  hyperparameter_tuning: true
  prediction_horizon: 1  # CHANGED FROM 12 TO 1
  prediction_target: direction
  retraining_frequency: weekly
  type: ensemble
  use_bayes_optimizer: true  # ADD THIS LINE
mt5:
  login: 145688
  password: "X9vyB7%90i"
  server: FusionMarkets-Demo
  timeout: 60000
risk:
  max_drawdown: 0.10
  max_open_positions: 2
  max_position_size: 0.01
  stop_loss: 0.02
  take_profit: 0.03
strategy:
  holding_periods:
    max: 48
    min: 4
  min_confidence: 0.75
  session_filters:
  - active: true
    name: low_liquidity
    sessions:
    - asian